language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"

env:
  - DJANGO_VERSION=Django==1.8.1
  - DJANGO_VERSION=Django==1.8.2
    # - 'DJANGO_VERSION="-e git+git://github.com/django/django.git#egg=Django"'

services:
  - "postgresql"

install: 
  - "pip install -r requirements.txt"
  - "pip install -q $DJANGO_VERSION"

script: "python manage.py test"
